// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/go-redis/redis"
	"github.com/jinzhu/gorm"
	"week04/internal/biz"
	"week04/internal/data"
	"week04/internal/service"
)

// Injectors from wire.go:

func InitializeOrderService(db *gorm.DB, cache *redis.Client) *service.Service {
	orderRepo := data.NewOrderRepo(db, cache)
	orderCase := biz.NewOrderBIZ(orderRepo)
	serviceService := service.NewService(orderCase)
	return serviceService
}
